/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Reconhecimento.Captura;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Agrotoxicos;
import model.InformacoesFiscais;
import model.Produtora;
import model.Usuario;
import org.bytedeco.javacv.FrameGrabber;

/**
 *
 * @author Lucas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Menu(String user,int nivel) {
        initComponents();
        lbBemvindo.setText("Bem vindo!," + user);
        if(nivel == 1){
            jTabbedPane1.remove(pnCadastro);
            jTabbedPane1.remove(pnNivel3);
            jTabbedPane1.remove(pnNivel2);         
        }
        else if(nivel == 2){
            jTabbedPane1.remove(pnCadastro);
            jTabbedPane1.remove(pnNivel3);         
        }
        
        
        
    }

    public Menu() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbBemvindo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnNivel1 = new javax.swing.JPanel();
        pnProducaoAgricola = new javax.swing.JPanel();
        tfNomeEmpresaN1 = new javax.swing.JTextField();
        btVerificarN1 = new javax.swing.JButton();
        lbNomeUsuario = new javax.swing.JLabel();
        pnProducao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpProducoesAgricolas = new javax.swing.JTextPane();
        pnNivel2 = new javax.swing.JPanel();
        pnInformacoesFiscais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeEmpresaN2 = new javax.swing.JTextField();
        btVerificarN2 = new javax.swing.JButton();
        pnFiscal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpFiscais = new javax.swing.JTextPane();
        pnNivel3 = new javax.swing.JPanel();
        pnAgrotoxicos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfNomeEmpresaN3 = new javax.swing.JTextField();
        btVerificarN3 = new javax.swing.JButton();
        pnAgrotoxico = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpAgrotoxicos = new javax.swing.JTextPane();
        pnCadastro = new javax.swing.JPanel();
        pnDados = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        lbNivel = new javax.swing.JLabel();
        cbNivel = new javax.swing.JComboBox<>();
        btBuscar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btListar1 = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        btListar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbBemvindo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbBemvindo.setForeground(new java.awt.Color(51, 102, 255));
        lbBemvindo.setText("Bem vindo!,");

        jTabbedPane1.setRequestFocusEnabled(false);

        pnProducaoAgricola.setBorder(javax.swing.BorderFactory.createTitledBorder("Produção AgrÍcolas"));

        tfNomeEmpresaN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeEmpresaN1ActionPerformed(evt);
            }
        });

        btVerificarN1.setText("Verificar");
        btVerificarN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificarN1ActionPerformed(evt);
            }
        });

        lbNomeUsuario.setText("Nome ou Código da Empresa :");

        pnProducao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setViewportView(tpProducoesAgricolas);

        javax.swing.GroupLayout pnProducaoLayout = new javax.swing.GroupLayout(pnProducao);
        pnProducao.setLayout(pnProducaoLayout);
        pnProducaoLayout.setHorizontalGroup(
            pnProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnProducaoLayout.setVerticalGroup(
            pnProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnProducaoAgricolaLayout = new javax.swing.GroupLayout(pnProducaoAgricola);
        pnProducaoAgricola.setLayout(pnProducaoAgricolaLayout);
        pnProducaoAgricolaLayout.setHorizontalGroup(
            pnProducaoAgricolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProducaoAgricolaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnProducaoAgricolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnProducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnProducaoAgricolaLayout.createSequentialGroup()
                        .addComponent(lbNomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeEmpresaN1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btVerificarN1)
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        pnProducaoAgricolaLayout.setVerticalGroup(
            pnProducaoAgricolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProducaoAgricolaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnProducaoAgricolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeUsuario)
                    .addComponent(tfNomeEmpresaN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerificarN1))
                .addGap(18, 18, 18)
                .addComponent(pnProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNivel1Layout = new javax.swing.GroupLayout(pnNivel1);
        pnNivel1.setLayout(pnNivel1Layout);
        pnNivel1Layout.setHorizontalGroup(
            pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNivel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnProducaoAgricola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNivel1Layout.setVerticalGroup(
            pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNivel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnProducaoAgricola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnProducaoAgricola.getAccessibleContext().setAccessibleName("Produção Agricolas");

        jTabbedPane1.addTab("Nivel 1", pnNivel1);

        pnInformacoesFiscais.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacões Fiscais"));

        jLabel1.setText("Nome ou Código da Empresa :");

        btVerificarN2.setText("Verificar");
        btVerificarN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificarN2ActionPerformed(evt);
            }
        });

        pnFiscal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane2.setViewportView(tpFiscais);

        javax.swing.GroupLayout pnFiscalLayout = new javax.swing.GroupLayout(pnFiscal);
        pnFiscal.setLayout(pnFiscalLayout);
        pnFiscalLayout.setHorizontalGroup(
            pnFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        pnFiscalLayout.setVerticalGroup(
            pnFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnInformacoesFiscaisLayout = new javax.swing.GroupLayout(pnInformacoesFiscais);
        pnInformacoesFiscais.setLayout(pnInformacoesFiscaisLayout);
        pnInformacoesFiscaisLayout.setHorizontalGroup(
            pnInformacoesFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformacoesFiscaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInformacoesFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInformacoesFiscaisLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeEmpresaN2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btVerificarN2))
                    .addComponent(pnFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnInformacoesFiscaisLayout.setVerticalGroup(
            pnInformacoesFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformacoesFiscaisLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnInformacoesFiscaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeEmpresaN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerificarN2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout pnNivel2Layout = new javax.swing.GroupLayout(pnNivel2);
        pnNivel2.setLayout(pnNivel2Layout);
        pnNivel2Layout.setHorizontalGroup(
            pnNivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNivel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnInformacoesFiscais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNivel2Layout.setVerticalGroup(
            pnNivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNivel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnInformacoesFiscais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nivel 2", pnNivel2);

        pnAgrotoxicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Agrotóxicos"));

        jLabel2.setText("Nome ou Código da Empresa : ");

        btVerificarN3.setText("Verificar");
        btVerificarN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificarN3ActionPerformed(evt);
            }
        });

        pnAgrotoxico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane3.setViewportView(tpAgrotoxicos);

        javax.swing.GroupLayout pnAgrotoxicoLayout = new javax.swing.GroupLayout(pnAgrotoxico);
        pnAgrotoxico.setLayout(pnAgrotoxicoLayout);
        pnAgrotoxicoLayout.setHorizontalGroup(
            pnAgrotoxicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        pnAgrotoxicoLayout.setVerticalGroup(
            pnAgrotoxicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnAgrotoxicosLayout = new javax.swing.GroupLayout(pnAgrotoxicos);
        pnAgrotoxicos.setLayout(pnAgrotoxicosLayout);
        pnAgrotoxicosLayout.setHorizontalGroup(
            pnAgrotoxicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAgrotoxicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAgrotoxicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnAgrotoxico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnAgrotoxicosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeEmpresaN3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVerificarN3)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnAgrotoxicosLayout.setVerticalGroup(
            pnAgrotoxicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAgrotoxicosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnAgrotoxicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNomeEmpresaN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerificarN3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnAgrotoxico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnNivel3Layout = new javax.swing.GroupLayout(pnNivel3);
        pnNivel3.setLayout(pnNivel3Layout);
        pnNivel3Layout.setHorizontalGroup(
            pnNivel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNivel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnAgrotoxicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNivel3Layout.setVerticalGroup(
            pnNivel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNivel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnAgrotoxicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nivel 3", pnNivel3);

        pnDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbNome.setText("Nome:");

        lbUsuario.setText("Usuario:");

        lbSenha.setText("Senha:");

        lbNivel.setText("Nivel:");

        cbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Nível", "Nível 1", "Nível 2", "Nível 3" }));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNome)
                    .addComponent(lbNome)
                    .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(lbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNivel)
                    .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addGap(141, 141, 141))
        );
        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDadosLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addGap(19, 19, 19)
                .addComponent(lbSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        btSalvar.setBackground(new java.awt.Color(153, 204, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(153, 204, 255));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(153, 204, 255));
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btListar1.setBackground(new java.awt.Color(153, 204, 255));
        btListar1.setText("Listar");
        btListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadastroLayout = new javax.swing.GroupLayout(pnCadastro);
        pnCadastro.setLayout(pnCadastroLayout);
        pnCadastroLayout.setHorizontalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnCadastroLayout.createSequentialGroup()
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnCadastroLayout.setVerticalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Cadastro", pnCadastro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBemvindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbBemvindo)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btListar.setBackground(new java.awt.Color(255, 204, 204));
        btListar.setText("Limpar Atual");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        btListar2.setBackground(new java.awt.Color(255, 204, 204));
        btListar2.setText("Limpar Tudo");
        btListar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btListar)
                .addGap(18, 18, 18)
                .addComponent(btListar2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirUsuario();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarUsuario();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        limpaCampo();
    }//GEN-LAST:event_btListarActionPerformed

    private void btListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListar1ActionPerformed
       
        telaConsulta tela = new telaConsulta();
        tela.setVisible(true);
        
    }//GEN-LAST:event_btListar1ActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        //        Verificacao se selecionou um nivel, caso não aparece mensagem de erro
        if(cbNivel.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Selecione um nível");
        }else{
            gravaUsuario();
            Random random = new Random();
            int numero = random. nextInt(100);
            //Inicia a captura da imagem
            try { 
                Captura cam = new Captura (numero);       
            } catch (FrameGrabber.Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try{
            consultaUsuario();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Esse usuario não existe");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tfNomeEmpresaN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeEmpresaN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeEmpresaN1ActionPerformed

    private void btVerificarN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificarN2ActionPerformed
        try{
            consultaInformacoesFiscais();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Esse registro não existe");
        } 
    }//GEN-LAST:event_btVerificarN2ActionPerformed

    private void btVerificarN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificarN3ActionPerformed
        try{
            consultaAgrotoxicos();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Esse registro não existe");
        }
    }//GEN-LAST:event_btVerificarN3ActionPerformed

    private void btVerificarN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificarN1ActionPerformed
        try{
            consultaTudo(tfNomeEmpresaN1.getText());
            tfNomeEmpresaN1.setText("");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Esse registro não existe");
        }
        
    }//GEN-LAST:event_btVerificarN1ActionPerformed

    private void btListar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListar2ActionPerformed
        limpaTodos();
    }//GEN-LAST:event_btListar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Menu().setVisible(true);
            }
        });
    }
       
    private void gravaUsuario(){
        String nome = tfNome.getText();
        String usuario = tfUsuario.getText();
        String senha = tfSenha.getText();
        int nivel = cbNivel.getSelectedIndex();
        
        System.out.println(new Usuario(nome,usuario,senha,nivel));
        
        limpaCampo();
        
        
    }
    
    private void limpaCampo(){
        int num = jTabbedPane1.getSelectedIndex();
        
        if(num == 0){
            tfNomeEmpresaN1.setText("");
            tpProducoesAgricolas.setText("");
        }
        else if(num == 1){
            tfNomeEmpresaN2.setText("");
            tpFiscais.setText("");
        }
        else if(num == 2){
            tfNomeEmpresaN3.setText("");
            tpAgrotoxicos.setText("");
        }
        else if(num == 3){
             tfNome.setText("");
            tfUsuario.setText("");
            tfSenha.setText("");
            cbNivel.setSelectedIndex(0);   
        }
    }
    
    private void limpaTodos(){
        tfNomeEmpresaN1.setText("");
        tpProducoesAgricolas.setText("");
        tfNomeEmpresaN2.setText("");
        tpFiscais.setText("");
        tfNomeEmpresaN3.setText("");
        tpAgrotoxicos.setText("");
        tfNome.setText("");
        tfUsuario.setText("");
        tfSenha.setText("");
        cbNivel.setSelectedIndex(0);
    }
    
    private void consultaUsuario(){
        
        Usuario usuario = new Usuario();
        usuario = dao.UsuarioDAO.getInstance().findByUsuario(tfUsuario.getText());
        tfNome.setText(usuario.getNome());
        tfSenha.setText(usuario.getSenha());
        cbNivel.setSelectedIndex(usuario.getNivel());
    
    }
    
    private void alterarUsuario(){
        String nome = tfNome.getText();
        String user = tfUsuario.getText();
        String senha = tfSenha.getText();
        int nivel = cbNivel.getSelectedIndex();
        
        Usuario usuario = new Usuario(nome,user,senha,nivel);
        dao.UsuarioDAO.getInstance().update(usuario);
        
        limpaCampo();
    }
    
    private void excluirUsuario(){
        dao.UsuarioDAO.getInstance().delete(tfUsuario.getText());
        limpaCampo();
    }
    
    private void consultaProdutora(){
        Produtora produtora = new Produtora();
        produtora = dao.ProdutoraDAO.getInstance().findByUsuario(tfNomeEmpresaN1.getText());
        tpProducoesAgricolas.setText(produtora.toString());
        tfNomeEmpresaN1.setText("");
    }
    
    private void consultaInformacoesFiscais() {
        if(validaBusca(tfNomeEmpresaN2.getText()) == true){
            InformacoesFiscais fiscais = new InformacoesFiscais(); 
            fiscais = dao.InformacoesFiscaisDAO.getInstance().findByUsuario(tfNomeEmpresaN2.getText());
            tpFiscais.setText(fiscais.toString());
            tfNomeEmpresaN2.setText("");
            tpProducoesAgricolas.setText("");
            tpAgrotoxicos.setText("");
        }else{
            InformacoesFiscais fiscais = new InformacoesFiscais(); 
            fiscais = dao.InformacoesFiscaisDAO.getInstance().findByCodigo(Integer.parseInt(tfNomeEmpresaN2.getText()));
            tpFiscais.setText(fiscais.toString());
            tfNomeEmpresaN2.setText("");
            tpProducoesAgricolas.setText("");
            tpAgrotoxicos.setText("");
        }
    }
    
    private void consultaAgrotoxicos() {
        if(validaBusca(tfNomeEmpresaN3.getText()) == true){
            Agrotoxicos agrotoxicos = new Agrotoxicos();
            agrotoxicos = dao.AgrotoxicosDAO.getInstance().findByUsuario(tfNomeEmpresaN3.getText());
            tpAgrotoxicos.setText(agrotoxicos.toString());
            tfNomeEmpresaN3.setText("");
            tpProducoesAgricolas.setText("");
            tpFiscais.setText("");
        }else{
            Agrotoxicos agrotoxicos = new Agrotoxicos();
            agrotoxicos = dao.AgrotoxicosDAO.getInstance().findByCodigo(Integer.parseInt(tfNomeEmpresaN3.getText()));
            tpAgrotoxicos.setText(agrotoxicos.toString());
            tfNomeEmpresaN3.setText("");
            tpProducoesAgricolas.setText("");
            tpFiscais.setText("");
        }
    }
    
    private void consultaTudo(String var){
        if(validaBusca(var) == true){
            Produtora produtora = new Produtora();
            InformacoesFiscais fiscais = new InformacoesFiscais();
            Agrotoxicos agrotoxicos = new Agrotoxicos();
            produtora = dao.ProdutoraDAO.getInstance().findByUsuario(var);
            fiscais = dao.InformacoesFiscaisDAO.getInstance().findByUsuario(var);
            agrotoxicos = dao.AgrotoxicosDAO.getInstance().findByUsuario(var);
            tpProducoesAgricolas.setText(produtora.toString());
            tpFiscais.setText(fiscais.toString());
            tpAgrotoxicos.setText(agrotoxicos.toString());
        }else{
            Produtora produtora = new Produtora();
            InformacoesFiscais fiscais = new InformacoesFiscais();
            Agrotoxicos agrotoxicos = new Agrotoxicos();
            produtora = dao.ProdutoraDAO.getInstance().findByCodigo(Integer.parseInt(var));
            fiscais = dao.InformacoesFiscaisDAO.getInstance().findByCodigo(Integer.parseInt(var));
            agrotoxicos = dao.AgrotoxicosDAO.getInstance().findByCodigo(Integer.parseInt(var));
            tpProducoesAgricolas.setText(produtora.toString());
            tpFiscais.setText(fiscais.toString());
            tpAgrotoxicos.setText(agrotoxicos.toString());
        }
    }
    
    private boolean validaBusca(String verificar){
        boolean res;
        
        if(verificar.matches("[0-999999]*"))
            res = false;
        else 
            res = true;
        
        return res;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btListar1;
    private javax.swing.JButton btListar2;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVerificarN1;
    private javax.swing.JButton btVerificarN2;
    private javax.swing.JButton btVerificarN3;
    private javax.swing.JComboBox<String> cbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbBemvindo;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel pnAgrotoxico;
    private javax.swing.JPanel pnAgrotoxicos;
    private javax.swing.JPanel pnCadastro;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnFiscal;
    private javax.swing.JPanel pnInformacoesFiscais;
    private javax.swing.JPanel pnNivel1;
    private javax.swing.JPanel pnNivel2;
    private javax.swing.JPanel pnNivel3;
    private javax.swing.JPanel pnProducao;
    private javax.swing.JPanel pnProducaoAgricola;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeEmpresaN1;
    private javax.swing.JTextField tfNomeEmpresaN2;
    private javax.swing.JTextField tfNomeEmpresaN3;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JTextField tfUsuario;
    private javax.swing.JTextPane tpAgrotoxicos;
    private javax.swing.JTextPane tpFiscais;
    private javax.swing.JTextPane tpProducoesAgricolas;
    // End of variables declaration//GEN-END:variables
}
